# Generated by Django 4.2.5 on 2023-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=40)),
                ('emailUsuario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='genero',
            new_name='generoArtista',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='nombre',
            new_name='nombreArtista',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fecha',
            new_name='fechaEvento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='lugar',
            new_name='lugarEvento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nombre',
            new_name='nombreEvento',
        ),
    ]
