# Generated by Django 4.2.5 on 2023-10-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0003_rename_fechaevento_evento_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('disciplina', models.CharField(max_length=40)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('artista', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
