# Generated by Django 4.2.5 on 2023-10-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0004_formulariocontacto_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='nombre',
            new_name='subtitulo',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='notas',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='notas',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
