# Generated by Django 4.2.5 on 2023-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0005_rename_nombre_notas_subtitulo_evento_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='texto',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='texto',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
