# Generated by Django 4.2.5 on 2023-10-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0008_evento_imagen2_evento_imagen3_notas_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='email',
        ),
        migrations.AddField(
            model_name='evento',
            name='artista',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='appExpe.artista'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='artista',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='appExpe.artista'),
        ),
    ]
