# Generated by Django 4.2.5 on 2023-10-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0009_remove_artista_apellido_remove_artista_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('direccion', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='appExpe.establecimiento'),
        ),
    ]
