# Generated by Django 4.2.5 on 2023-10-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0010_establecimiento_alter_evento_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='appExpe.establecimiento'),
        ),
    ]
