# Generated by Django 4.2.5 on 2023-10-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0012_alter_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='appExpe\\static\\images'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='appExpe\\static\\images'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='appExpe\\static\\images'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='appExpe\\static\\images'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='appExpe\\static\\images'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='appExpe\\static\\images'),
        ),
    ]
