# Generated by Django 4.2.5 on 2023-10-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0013_alter_evento_imagen_alter_evento_imagen2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='artista',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
