# Generated by Django 4.2.5 on 2023-10-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0014_delete_usuario_artista_descripcion_artista_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
