# Generated by Django 4.2.5 on 2023-10-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0016_artista_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
