# Generated by Django 4.2.5 on 2023-10-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0017_alter_artista_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='appExpe\\static\\images'),
        ),
    ]
