# Generated by Django 4.2.5 on 2023-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0019_alter_artista_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariocontacto',
            name='disciplina',
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='mensaje',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
