# Generated by Django 4.2.5 on 2023-10-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0020_remove_formulariocontacto_disciplina_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormularioContacto',
            new_name='Contacto',
        ),
    ]
