# Generated by Django 4.2.5 on 2023-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appExpe', '0021_rename_formulariocontacto_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
